name = "airui-angular"
type = "webpack"
account_id = "792461088a4c863230f3faee467094b1"
# workers_dev = true
route = "angular.airui.cloud/*"
zone_id = "e32c3c89723adb66f1b86027a9a8d9db"

[site]
bucket = "../dist"
entry-point = "workers-site"
